AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ProductCRUDFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.productHandler
      Runtime: nodejs8.10
      Events:
        ProductPostAPI:
          Type: Api
          Properties:
            Path: /product
            Method: POST
        ProductGetAPI:
          Type: Api
          Properties:
            Path: /product/{productId}
            Method: ANY
        
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/inkProductsTable'


  inkProductsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: inkProductsTable
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5  